# Generated by Django 5.1.2 on 2024-10-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwd_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistancerequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='user',
        ),
    ]
