# Generated by Django 5.1.2 on 2024-10-16 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_users', 'Can view users'), ('can_edit_users', 'Can edit users')]},
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usertoken',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('pwd', 'Person with Disability'), ('volunteer', 'Assistance Volunteer'), ('paid', 'Assistance Paid')], max_length=50),
        ),
    ]
